version: '3.1'
services :
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
  admin:
    image: adminer
    depends_on: 
      - db
    ports:
      - 8080:8080

